# Codecov for main is visible here https://app.codecov.io/gh/tetratelabs/wazero

# We use codecov only as a UI, so we disable PR comments.
# See https://docs.codecov.com/docs/pull-request-comments
comment: false
