package experimental_test

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"log"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/experimental"
)

// fuelWasm was generated by the following:
//
//	cd testdata; wat2wasm fuel.wat
//
//go:embed testdata/fuel.wasm
var fuelWasm []byte

// ExampleSetFuel computes fibonacci with growing arguments, refueling
// between calls, until one call exhausts the budget.
func ExampleSetFuel() {
	ctx := context.Background()

	// Fuel is honored only by the interpreter engine.
	r := wazero.NewRuntimeWithConfig(ctx, wazero.NewRuntimeConfigInterpreter())
	defer r.Close(ctx)

	mod, err := r.Instantiate(ctx, fuelWasm)
	if err != nil {
		log.Panicln(err)
	}
	fib := mod.ExportedFunction("fibonacci")

	ctx = experimental.SetFuel(ctx, 10_000)

	for n := uint64(1); ; n++ {
		before := experimental.GetFuel(ctx)
		out, err := fib.Call(ctx, n)
		if errors.Is(err, experimental.ErrOutOfFuel) {
			fmt.Printf("Exhausted fuel computing fib(%d)\n", n)
			break
		}
		if err != nil {
			log.Panicln(err)
		}
		fmt.Printf("fib(%d) = %d [consumed %d fuel]\n",
			n, int32(out[0]), before-experimental.GetFuel(ctx))
		experimental.SetFuel(ctx, 10_000) // refuel
	}

	// Output:
	// fib(1) = 1 [consumed 10 fuel]
	// fib(2) = 1 [consumed 38 fuel]
	// fib(3) = 2 [consumed 66 fuel]
	// fib(4) = 3 [consumed 122 fuel]
	// fib(5) = 5 [consumed 206 fuel]
	// fib(6) = 8 [consumed 346 fuel]
	// fib(7) = 13 [consumed 570 fuel]
	// fib(8) = 21 [consumed 934 fuel]
	// fib(9) = 34 [consumed 1522 fuel]
	// fib(10) = 55 [consumed 2474 fuel]
	// fib(11) = 89 [consumed 4014 fuel]
	// fib(12) = 144 [consumed 6506 fuel]
	// Exhausted fuel computing fib(13)
}
